export const LOAD_POST_START = 'LOAD_POST_START';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const LOAD_POST_FAIL = 'LOAD_POST_FAIL';

export const LOAD_POST_BY_ID_START = 'LOAD_POST_BY_ID_START';
export const LOAD_POST_BY_ID_SUCCESS = 'LOAD_POST_BY_ID_SUCCESS';
export const LOAD_POST_BY_ID_FAIL = 'LOAD_POST_BY_ID_FAIL';

export const LOAD_POST_BY_USER_START = 'LOAD_POST_BY_USER_START';
export const LOAD_POST_BY_USER_SUCCESS = 'LOAD_POST_BY_USER_SUCCESS';
export const LOAD_POST_BY_USER_FAIL = 'LOAD_POST_BY_USER_FAIL';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
