export const LOAD_COMMENT_START = 'LOAD_COMMENT_START';
export const LOAD_COMMENT_SUCCESS = 'LOAD_COMMENT_SUCCESS';
export const LOAD_COMMENT_FAIL = 'LOAD_COMMENT_FAIL';
export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const GET_COMMENT_BY_POST_ID = 'GET_COMMENT_BY_POST_ID';
