export const LOAD_COMMENT_START = 'LOAD_COMMENT_START';
export const LOAD_COMMENT_SUCCESS = 'LOAD_COMMENT_SUCCESS';
export const LOAD_COMMENT_FAIL = 'LOAD_COMMENT_FAIL';
export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const DELETE_COMMENT = 'DELETE_COMMENT';

